### ISSUE TITLE
Ошибка кодировки в логах

### ISSUE THREAD

**Issue by Overflow922** [Overflow922/notification-bot#24]
Сейчас в логах выводится неверная кодировка:

2023-04-26 19:07:30.805 ERROR 1 --- [legram Executor] c.i.n.services.NotificationBotService    : РџСЂРѕРёР·РѕС€Р»Р° РѕС€РёР±РєР°.

**Comment by temychpp** [comment]
https://ru.stackoverflow.com/questions/1258031/%D0%9D%D0%B5-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D0%B5%D1%82%D1%81%D1%8F-%D0%BA%D0%B8%D1%80%D0%B8%D0%BB%D0%B8%D1%86%D0%B0-%D0%B2-%D0%BA%D0%BE%D0%BD%D1%81%D0%BE%D0%BB%D0%B8
